version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rollup
    versions:
    - 2.40.0
    - 2.41.2
    - 2.42.3
    - 2.44.0
    - 2.45.1
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.9
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: "@rollup/plugin-node-resolve"
    versions:
    - 11.2.0
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.0.0
    - 17.1.0
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.0.3
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: "@types/react-test-renderer"
    versions:
    - 17.0.0
