version: 2.1

workflows:
  version: 2
  test-lint-typecheck:
    jobs:
      - bundle_npm_dependencies
      - test:
          requires:
            - bundle_npm_dependencies
      - lint:
          requires:
            - bundle_npm_dependencies
      - typecheck:
          requires:
            - bundle_npm_dependencies

jobs:
  bundle_npm_dependencies:
    docker:
      - image: circleci/node:12
    working_directory: ~/react-use-kana
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: yarn install
          command: |
            yarn install
      - save_cache:
          paths:
            - ~/react-use-kana/node_modules
          key: npm-v1-dependencies-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:12
    working_directory: ~/react-use-kana
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: tests
          command: |
            yarn test

  lint:
    docker:
      - image: circleci/node:12
    working_directory: ~/react-use-kana
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: lint
          command: |
            yarn eslint -- --format junit -o reports/junit/js-lint-results.xml
      - store_test_results:
          path: react-use-kana/reports/junit
      - store_artifacts:
          path: react-use-kana/reports/junit

  typecheck:
    docker:
      - image: circleci/node:12
    working_directory: ~/react-use-kana
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-v1-dependencies-{{ checksum "yarn.lock" }}
            - npm-v1-dependencies-
      - run:
          name: typecheck
          command: |
            yarn typecheck
